---

uiStyle:
  toolbar:
    background: ""
    item:
      selected: { img: ui/slant_capsule.png, colour: $toolbarSelected }
      hover: { img: ui/slant_capsule.png, colour: $toolbarHover }
      normal: { img: ui/slant_capsule.png, colour: $toolbarNormal }
      innerBorder: [ 8, 1, 8, 1 ]
    innerBorder: [ 0, 0, 0, 0 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    selectionChangedSound: ""
    label: { font: Ubuntu Bold, size: 18, colour: $toolbarText }
    selectedImageColour: $toolbarIconSelected
    imageColour: $toolbarIconNormal
    gap: -5

  flatButton:
    normal: { img: whitebox.png, colour: "#00000000" }
    down: { img: whitebox.png, colour: "#00000000" }
    hover: { img: whitebox.png, colour: "#00000000" }
    innerBorder: [ 0, 0, 0, 0 ]
    upSound: ""
    downSound: ""
    hoverSound: ""
    label: { font: Ubuntu Bold, size: 18, colour: $toolbarText }
    labelBorder: [0, 0, 0, 0]
    iconBorder: [0, 0, 0, 0]
    hoveredIconColour: $toolbarIconHover

  slantButton:
    selected: { img: ui/slant_capsule.png, colour: $toolbarSelected }
    hover: { img: ui/slant_capsule.png, colour: $toolbarHover }
    normal: { img: ui/slant_capsule.png, colour: $toolbarNormal }
    down: { img: ui/slant_capsule.png, colour: $toolbarDown }
    innerBorder: [ 15, 0, 15, 0 ]
    upSound: ""
    downSound: ""
    hoverSound: ""
    label: { font: Ubuntu Bold, size: 18, colour: $toolbarText }
    labelBorder: [0, 0, 0, 0]
    iconBorder: [0, 0, 0, 0]
    hoveredIconColour: $toolbarIconHover

...