name: Light Glass
base: colour_schemes/base_light
colours:
  background0: "#F5F5F5"
  background1: "#F8F8F8"
  backgroundLogo: "#F3F3F3"

  ui_controlNormal: "#A2A0A9"
  ui_controlDown: "#7A7984"
  ui_controlHover: "#BBBBC1"
  ui_controlDisabled: "#CFCFCF"
  
  ui_buttonNormal: "#A2A0A9"
  ui_buttonDown: "#7A7984"
  ui_buttonHover: "#BBBBC1"
  ui_buttonDisabled: "#CFCFCF"

  ui_inputNormal: "#A2A0A9"
  ui_inputDown: "#7A7984"
  ui_inputHover: "#BBBBC1"
  ui_inputDisabled: "#CFCFCF"

  ui_listBackground: "#CFCFD380"
  ui_listSelected: "#FFFFFF"
  ui_listHover: "#F0F0F4"
  ui_listDrag: "#A2A0A980"

  ui_scrollBackground: "#EBEBEDD0"
  ui_backgroundBox: "#EBEBED80"
  ui_popupWindow: "#DFDFE6D0"
  ui_staticBox: "#DFDFE6D0"
  ui_staticBoxSubdue: "#CFCFD6D0"

  ui_debugConsole: "#A2A0A9C0"
