---
widget: { class: widget }
sizer: { type: horizontal }
proportion: 1
children:
- sizer: { type: vertical }
  children:
    - widget: { id: scrollBarPane, class: scrollBarPane, scrollHorizontal: true, scrollVertical: true, size: [350, 22] }
      sizer: { type: vertical }
      proportion: 1
      children:
        - widget: { id: entityList, class: entityList }
          proportion: 1
    - sizer: { type: horizontal }
      children:
        - widget: { id: addEntity, class: button, text: Add Entity, tooltip: "Adds a blank new entity as a child of the current selection." }
          proportion: 1
        - widget: { id: addPrefab, class: button, text: Add Prefab, tooltip: "Adds a Prefab as a child of the current selection." }
          proportion: 1
        - widget: { id: removeEntity, class: button, text: Remove, tooltip: "Removes the currently selected entity." }
          proportion: 1
- sizer: { type: vertical}
  proportion: 1
  children:
    - widget: { id: sceneEditorToolbar, class: image, image: "halley_ui/ui_list_item.png", colour: $ui_backgroundBox, innerBorder: [5, 5, 5, 5] }
      sizer: { type: horizontal }
      children:
        - widget: { id: saveButton, class: button, style: buttonThin, text: "Save", size: [100, 22], tooltip: "Save [Ctrl+S]" }
        - border: [10, 0, 0, 0]
          widget:
            id: toolMode
            class: list
            type: horizontal
            options:
              - id: drag
                image: ui/scene_editor_drag.png
                tooltip: Pan Scene
              - id: translate
                image: ui/scene_editor_move.png
                tooltip: Move Entities
              - id: polygon
                image: ui/scene_editor_polygon.png
                tooltip: Edit Polygon
              - id: vertex
                image: ui/scene_editor_polygon.png
                tooltip: Edit Vertex
    - widget: { id: canvas, class: sceneEditorCanvas }
      proportion: 1
      sizer: { type: vertical }
      children:
        - widget: { id: currentToolUI, class: image, image: "halley_ui/ui_list_item.png", colour: $ui_backgroundBox, innerBorder: [5, 5, 5, 5], size: [100, 32] }
          sizer: { type: horizontal }
          border: [10, 10, 10, 10]
          fill: right
          children: []
        - widget: { id: debugConsole, class: debugConsole, size: [640, 320], active: false }
          proportion: 1
          border: [10, 10, 10, 10]
          fill: [ bottom, left ]
    - widget: { id: customUI, class: widget }
      sizer: { type: vertical }
      children: []
- widget: { id: entityEditor, class: entityEditor }
...